[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[[language]]
name = "python"
language-servers = ["ty","scls"]
formatter = { command = "ruff", args = ["format", '-']}
auto-format = true

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "scls"]
