[tools]
bob = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
helix = "latest"
lazygit = "latest"
node = "22"
python = "latest"
ripgrep = "latest"
rust = "stable"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
zig = "latest"
