[tools]
aws = { version = "latest", symlink_bins = "true" }
bob = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
helix = "latest"
lazygit = "latest"
node = "22"
python = "latest"
ripgrep = "latest"
rust = "latest"
terraform = "latest"
terraform-ls = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
zig = "latest"
